<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Dtos\**" />
    <EmbeddedResource Remove="Dtos\**" />
    <None Remove="Dtos\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BCrypt.Net-Core" />
    <PackageReference Include="FluentValidation" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FgcGames.Domain\FgcGames.Domain.csproj" />
    <ProjectReference Include="..\FgcGames.Shared\FgcGames.Shared.csproj" />
  </ItemGroup>

</Project>
