<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>3a64d3e4-6f15-478c-a4f1-2614be65c71d</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" />
    <PackageReference Include="Serilog.AspNetCore" />
    <PackageReference Include="Serilog.Sinks.Console" />
    <PackageReference Include="Serilog.Sinks.File" />
    <PackageReference Include="Serilog.Sinks.OpenTelemetry" />
    <PackageReference Include="Swashbuckle.AspNetCore" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\FgcGames.Application\FgcGames.Application.csproj" />
    <ProjectReference Include="..\FgcGames.Domain\FgcGames.Domain.csproj" />
    <ProjectReference Include="..\FgcGames.Infra\FgcGames.Infra.csproj" />
    <ProjectReference Include="..\FgcGames.IoC\FgcGames.IoC.csproj" />
    <ProjectReference Include="..\FgcGames.ServiceDefaults\FgcGames.ServiceDefaults.csproj" />
    <ProjectReference Include="..\FgcGames.Shared\FgcGames.Shared.csproj" />
  </ItemGroup>

</Project>
