// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace FgcGames.BDDTests.Features.Jogos
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::NUnit.Framework.TestFixtureAttribute()]
    [global::NUnit.Framework.DescriptionAttribute("Atualizar Jogo")]
    [global::NUnit.Framework.FixtureLifeCycleAttribute(global::NUnit.Framework.LifeCycle.InstancePerTestCase)]
    public partial class AtualizarJogoFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features/Jogos", "Atualizar Jogo", "  Como administrador do sistema\r\n  Quero atualizar os dados dos jogos\r\n  Para man" +
                "ter o catálogo correto", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "AtualizarJogo.feature"
#line hidden
        
        [global::NUnit.Framework.OneTimeSetUpAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [global::NUnit.Framework.OneTimeTearDownAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        [global::NUnit.Framework.SetUpAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [global::NUnit.Framework.TearDownAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::NUnit.Framework.TestContext>(global::NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async global::System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 6
  #line hidden
#line 7
    await testRunner.GivenAsync("estou autenticado como \"admin@fgcgames.com\" com senha \"Abc!1234\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 8
    await testRunner.AndAsync("existe um jogo cadastrado com nome \"Dark Souls\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
        }
        
        private static global::Io.Cucumber.Messages.Types.Source SourceFunc()
        {
            return new global::Io.Cucumber.Messages.Types.Source("Features/Jogos/AtualizarJogo.feature", @"Feature: Atualizar Jogo
  Como administrador do sistema
  Quero atualizar os dados dos jogos
  Para manter o catálogo correto

  Background:
    Given estou autenticado como ""admin@fgcgames.com"" com senha ""Abc!1234""
    And existe um jogo cadastrado com nome ""Dark Souls""

  Scenario: Admin atualiza jogo com dados válidos retorna 204
    When atualizo o jogo com nome ""Dark Souls Remastered"", descrição ""Versão remasterizada"", preço 149.90, lançamento ""2018-05-25"" e classificação 16
    Then a resposta deve ter status 204

  Scenario: Atualizar jogo inexistente retorna 404
    When atualizo o jogo com ID ""00000000-0000-0000-0000-000000000004"" com nome ""Teste""
    Then a resposta deve ter status 404

  Scenario: Usuário comum não pode atualizar jogo retorna 403
    Given estou autenticado como ""user@fgcgames.com"" com senha ""Abc!1234""
    When atualizo o jogo com nome ""Novo Nome"", descrição ""Desc"", preço 99.90, lançamento ""2020-01-01"" e classificação 0
    Then a resposta deve ter status 403

  Scenario: Admin altera preço do jogo retorna 204
    When altero o preço do jogo para 89.90
    Then a resposta deve ter status 204

  Scenario: Alterar preço de jogo inexistente retorna 404
    When altero o preço do jogo com ID ""00000000-0000-0000-0000-000000000005"" para 50.00
    Then a resposta deve ter status 404
", global::Io.Cucumber.Messages.Types.SourceMediaType.TEXT_X_CUCUMBER_GHERKIN_PLAIN);
        }
        
        private static global::Io.Cucumber.Messages.Types.GherkinDocument GherkinDocumentFunc()
        {
            return new global::Io.Cucumber.Messages.Types.GherkinDocument("Features/Jogos/AtualizarJogo.feature", new global::Io.Cucumber.Messages.Types.Feature(new global::Io.Cucumber.Messages.Types.Location(1, new System.Nullable<long>(1)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "en-US", "Feature", "Atualizar Jogo", "  Como administrador do sistema\r\n  Quero atualizar os dados dos jogos\r\n  Para man" +
                        "ter o catálogo correto", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.FeatureChild>(new global::Io.Cucumber.Messages.Types.FeatureChild[] {
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, new global::Io.Cucumber.Messages.Types.Background(new global::Io.Cucumber.Messages.Types.Location(6, new System.Nullable<long>(3)), "Background", "", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(7, new System.Nullable<long>(5)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "estou autenticado como \"admin@fgcgames.com\" com senha \"Abc!1234\"", null, null, "fdb640e27e4dbe50bef6dd591b11dffc"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(8, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "existe um jogo cadastrado com nome \"Dark Souls\"", null, null, "a128110749850d51974b7c087921dd86")}), "47f455181fcdba5db0a9c67432a42c4a"), null),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(10, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "Scenario", "Admin atualiza jogo com dados válidos retorna 204", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(11, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "atualizo o jogo com nome \"Dark Souls Remastered\", descrição \"Versão remasterizada" +
                                                            "\", preço 149.90, lançamento \"2018-05-25\" e classificação 16", null, null, "7df55208a41ef758be799b7387f1446d"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(12, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "a resposta deve ter status 204", null, null, "e9512c4eb468e553bdfb7b825e16e916")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "52f4442206cdf75684ba57861832b7c8")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(14, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "Scenario", "Atualizar jogo inexistente retorna 404", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(15, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "atualizo o jogo com ID \"00000000-0000-0000-0000-000000000004\" com nome \"Teste\"", null, null, "b92e014635a21153801af3df505ac523"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(16, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "a resposta deve ter status 404", null, null, "ef4725fc2a20975b8522b0404477c5d7")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "98fdd8167b60295dbdc5de16528f1130")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(18, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "Scenario", "Usuário comum não pode atualizar jogo retorna 403", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(19, new System.Nullable<long>(5)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "estou autenticado como \"user@fgcgames.com\" com senha \"Abc!1234\"", null, null, "2b68f1516c678e5dac97a48da2fc549c"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(20, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "atualizo o jogo com nome \"Novo Nome\", descrição \"Desc\", preço 99.90, lançamento \"" +
                                                            "2020-01-01\" e classificação 0", null, null, "11c1107c9bbbae51a56321c7fe6fd0e7"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(21, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "a resposta deve ter status 403", null, null, "209f9cdcb7845e56ac25cdf61ac4fb69")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "7ef4768be227e95bb1a48351ece08f41")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(23, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "Scenario", "Admin altera preço do jogo retorna 204", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(24, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "altero o preço do jogo para 89.90", null, null, "8d397879f06d245c91e1cabaa730a9e9"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(25, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "a resposta deve ter status 204", null, null, "17d708dc83be155a865e96665fbe6ec4")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "7332b70bfa5b2c558fa49c561f2a4370")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(27, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "Scenario", "Alterar preço de jogo inexistente retorna 404", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(28, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "altero o preço do jogo com ID \"00000000-0000-0000-0000-000000000005\" para 50.00", null, null, "183c84b44434ef50a007302f2aebc7d6"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(29, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "a resposta deve ter status 404", null, null, "870398626ea868528e11138f1018621e")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "d6221e1843f1af56b066d6429940960b"))})), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Comment>(new global::Io.Cucumber.Messages.Types.Comment[0]));
        }
        
        private static global::System.Collections.Generic.IEnumerable<Io.Cucumber.Messages.Types.Pickle> PicklesFunc()
        {
            return new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Pickle>(new global::Io.Cucumber.Messages.Types.Pickle[] {
                        new global::Io.Cucumber.Messages.Types.Pickle("4e41e4c4efbbe954aef223c0100b6fbc", "Features/Jogos/AtualizarJogo.feature", "Admin atualiza jogo com dados válidos retorna 204", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "fdb640e27e4dbe50bef6dd591b11dffc"}), "5a6386c61cc122538c77daa889927677", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "estou autenticado como \"admin@fgcgames.com\" com senha \"Abc!1234\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "a128110749850d51974b7c087921dd86"}), "4521ef7fe0ccbe50baf0aff82ea82779", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "existe um jogo cadastrado com nome \"Dark Souls\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "7df55208a41ef758be799b7387f1446d"}), "a378d9e79e542659ae43bbd157a6481a", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "atualizo o jogo com nome \"Dark Souls Remastered\", descrição \"Versão remasterizada" +
                                                "\", preço 149.90, lançamento \"2018-05-25\" e classificação 16"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "e9512c4eb468e553bdfb7b825e16e916"}), "bb20422a32f31a53a274925119ac2c85", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "a resposta deve ter status 204")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[0]), new System.Collections.Generic.List<string>(new string[] {
                                        "52f4442206cdf75684ba57861832b7c8"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("90b1ea3bdbd4925aa685dd924d6c0da0", "Features/Jogos/AtualizarJogo.feature", "Atualizar jogo inexistente retorna 404", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "fdb640e27e4dbe50bef6dd591b11dffc"}), "dc42548a0e04ce5c8eeac677e77e1855", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "estou autenticado como \"admin@fgcgames.com\" com senha \"Abc!1234\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "a128110749850d51974b7c087921dd86"}), "44c2efeda8ccb650a40c0b2af9184af2", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "existe um jogo cadastrado com nome \"Dark Souls\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "b92e014635a21153801af3df505ac523"}), "20bab2464e7e1a5eae1c712d48b40d78", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "atualizo o jogo com ID \"00000000-0000-0000-0000-000000000004\" com nome \"Teste\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "ef4725fc2a20975b8522b0404477c5d7"}), "cee9947b39ab8c5aad5ef7eaf2198639", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "a resposta deve ter status 404")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[0]), new System.Collections.Generic.List<string>(new string[] {
                                        "98fdd8167b60295dbdc5de16528f1130"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("128507cb3353565580c1c9779714927e", "Features/Jogos/AtualizarJogo.feature", "Usuário comum não pode atualizar jogo retorna 403", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "fdb640e27e4dbe50bef6dd591b11dffc"}), "c0d834d001274851b43547b68479d8f2", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "estou autenticado como \"admin@fgcgames.com\" com senha \"Abc!1234\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "a128110749850d51974b7c087921dd86"}), "43b82f14952bba52a76f846603a0b26e", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "existe um jogo cadastrado com nome \"Dark Souls\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "2b68f1516c678e5dac97a48da2fc549c"}), "7df5cc22e0e1025ebc2d50e468dcf40f", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "estou autenticado como \"user@fgcgames.com\" com senha \"Abc!1234\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "11c1107c9bbbae51a56321c7fe6fd0e7"}), "724c39b84fc8c45f9339f4058b83665a", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "atualizo o jogo com nome \"Novo Nome\", descrição \"Desc\", preço 99.90, lançamento \"" +
                                                "2020-01-01\" e classificação 0"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "209f9cdcb7845e56ac25cdf61ac4fb69"}), "deb6b4762a282a5caf3d9b707b678b8d", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "a resposta deve ter status 403")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[0]), new System.Collections.Generic.List<string>(new string[] {
                                        "7ef4768be227e95bb1a48351ece08f41"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("c35d555c16b1775f8bd140e941db1648", "Features/Jogos/AtualizarJogo.feature", "Admin altera preço do jogo retorna 204", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "fdb640e27e4dbe50bef6dd591b11dffc"}), "2b25e75077caec51b4c6a9ac616ffffc", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "estou autenticado como \"admin@fgcgames.com\" com senha \"Abc!1234\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "a128110749850d51974b7c087921dd86"}), "9916b1c73980e75b99bd032177143240", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "existe um jogo cadastrado com nome \"Dark Souls\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "8d397879f06d245c91e1cabaa730a9e9"}), "4317ee74ee13ed52944467a7d90d7e91", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "altero o preço do jogo para 89.90"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "17d708dc83be155a865e96665fbe6ec4"}), "a38635ab28287d56b40d1113d3d42edb", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "a resposta deve ter status 204")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[0]), new System.Collections.Generic.List<string>(new string[] {
                                        "7332b70bfa5b2c558fa49c561f2a4370"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("5b975a036f99d556abfd17f752e7ea1c", "Features/Jogos/AtualizarJogo.feature", "Alterar preço de jogo inexistente retorna 404", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "fdb640e27e4dbe50bef6dd591b11dffc"}), "0b85d791c3f7b85e85dc13987dccc69c", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "estou autenticado como \"admin@fgcgames.com\" com senha \"Abc!1234\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "a128110749850d51974b7c087921dd86"}), "aec0e9cce1e9315495e22f1934a7f201", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "existe um jogo cadastrado com nome \"Dark Souls\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "183c84b44434ef50a007302f2aebc7d6"}), "ba3f506c72794b5a9bbe9a881b803ca1", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "altero o preço do jogo com ID \"00000000-0000-0000-0000-000000000005\" para 50.00"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "870398626ea868528e11138f1018621e"}), "2e371231d26aa6529c0f1fb7ce1d3b8d", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "a resposta deve ter status 404")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[0]), new System.Collections.Generic.List<string>(new string[] {
                                        "d6221e1843f1af56b066d6429940960b"}))});
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages(new global::System.Func<Io.Cucumber.Messages.Types.Source>(AtualizarJogoFeature.SourceFunc), new global::System.Func<Io.Cucumber.Messages.Types.GherkinDocument>(AtualizarJogoFeature.GherkinDocumentFunc), new global::System.Func<System.Collections.Generic.IEnumerable<Io.Cucumber.Messages.Types.Pickle>>(AtualizarJogoFeature.PicklesFunc));
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Admin atualiza jogo com dados válidos retorna 204")]
        public async global::System.Threading.Tasks.Task AdminAtualizaJogoComDadosValidosRetorna204()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Admin atualiza jogo com dados válidos retorna 204", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 10
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 11
    await testRunner.WhenAsync("atualizo o jogo com nome \"Dark Souls Remastered\", descrição \"Versão remasterizada" +
                        "\", preço 149.90, lançamento \"2018-05-25\" e classificação 16", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 12
    await testRunner.ThenAsync("a resposta deve ter status 204", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Atualizar jogo inexistente retorna 404")]
        public async global::System.Threading.Tasks.Task AtualizarJogoInexistenteRetorna404()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Atualizar jogo inexistente retorna 404", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 14
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 15
    await testRunner.WhenAsync("atualizo o jogo com ID \"00000000-0000-0000-0000-000000000004\" com nome \"Teste\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 16
    await testRunner.ThenAsync("a resposta deve ter status 404", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Usuário comum não pode atualizar jogo retorna 403")]
        public async global::System.Threading.Tasks.Task UsuarioComumNaoPodeAtualizarJogoRetorna403()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Usuário comum não pode atualizar jogo retorna 403", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 18
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 19
    await testRunner.GivenAsync("estou autenticado como \"user@fgcgames.com\" com senha \"Abc!1234\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 20
    await testRunner.WhenAsync("atualizo o jogo com nome \"Novo Nome\", descrição \"Desc\", preço 99.90, lançamento \"" +
                        "2020-01-01\" e classificação 0", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 21
    await testRunner.ThenAsync("a resposta deve ter status 403", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Admin altera preço do jogo retorna 204")]
        public async global::System.Threading.Tasks.Task AdminAlteraPrecoDoJogoRetorna204()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "3";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Admin altera preço do jogo retorna 204", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 23
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 24
    await testRunner.WhenAsync("altero o preço do jogo para 89.90", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 25
    await testRunner.ThenAsync("a resposta deve ter status 204", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Alterar preço de jogo inexistente retorna 404")]
        public async global::System.Threading.Tasks.Task AlterarPrecoDeJogoInexistenteRetorna404()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "4";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Alterar preço de jogo inexistente retorna 404", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 27
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 28
    await testRunner.WhenAsync("altero o preço do jogo com ID \"00000000-0000-0000-0000-000000000005\" para 50.00", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 29
    await testRunner.ThenAsync("a resposta deve ter status 404", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
