// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace FgcGames.BDDTests.Features.Jogos
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::NUnit.Framework.TestFixtureAttribute()]
    [global::NUnit.Framework.DescriptionAttribute("Buscar Jogo")]
    [global::NUnit.Framework.FixtureLifeCycleAttribute(global::NUnit.Framework.LifeCycle.InstancePerTestCase)]
    public partial class BuscarJogoFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features/Jogos", "Buscar Jogo", "  Como usuário autenticado\r\n  Quero buscar jogos cadastrados\r\n  Para visualizar o" +
                " catálogo disponível", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "BuscarJogo.feature"
#line hidden
        
        [global::NUnit.Framework.OneTimeSetUpAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [global::NUnit.Framework.OneTimeTearDownAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        [global::NUnit.Framework.SetUpAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [global::NUnit.Framework.TearDownAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::NUnit.Framework.TestContext>(global::NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async global::System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 6
  #line hidden
#line 7
    await testRunner.GivenAsync("estou autenticado como \"admin@fgcgames.com\" com senha \"Abc!1234\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 8
    await testRunner.AndAsync("existe um jogo cadastrado com nome \"God of War\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
        }
        
        private static global::Io.Cucumber.Messages.Types.Source SourceFunc()
        {
            return new global::Io.Cucumber.Messages.Types.Source("Features/Jogos/BuscarJogo.feature", @"Feature: Buscar Jogo
  Como usuário autenticado
  Quero buscar jogos cadastrados
  Para visualizar o catálogo disponível

  Background:
    Given estou autenticado como ""admin@fgcgames.com"" com senha ""Abc!1234""
    And existe um jogo cadastrado com nome ""God of War""

  Scenario: Listar todos os jogos retorna 200
    When listo todos os jogos
    Then a resposta deve ter status 200
    And a resposta deve conter uma lista de jogos

  Scenario: Buscar jogo por ID existente retorna 200
    When busco o jogo pelo ID
    Then a resposta deve ter status 200
    And a resposta deve conter os dados do jogo

  Scenario: Buscar jogo por ID inexistente retorna 404
    When busco o jogo com ID ""00000000-0000-0000-0000-000000000003""
    Then a resposta deve ter status 404

  Scenario: Usuário comum pode listar jogos retorna 200
    Given estou autenticado como ""user@fgcgames.com"" com senha ""Abc!1234""
    When listo todos os jogos
    Then a resposta deve ter status 200

  Scenario: Requisição sem autenticação não pode listar jogos retorna 401
    Given não estou autenticado
    When listo todos os jogos
    Then a resposta deve ter status 401
", global::Io.Cucumber.Messages.Types.SourceMediaType.TEXT_X_CUCUMBER_GHERKIN_PLAIN);
        }
        
        private static global::Io.Cucumber.Messages.Types.GherkinDocument GherkinDocumentFunc()
        {
            return new global::Io.Cucumber.Messages.Types.GherkinDocument("Features/Jogos/BuscarJogo.feature", new global::Io.Cucumber.Messages.Types.Feature(new global::Io.Cucumber.Messages.Types.Location(1, new System.Nullable<long>(1)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "en-US", "Feature", "Buscar Jogo", "  Como usuário autenticado\r\n  Quero buscar jogos cadastrados\r\n  Para visualizar o" +
                        " catálogo disponível", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.FeatureChild>(new global::Io.Cucumber.Messages.Types.FeatureChild[] {
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, new global::Io.Cucumber.Messages.Types.Background(new global::Io.Cucumber.Messages.Types.Location(6, new System.Nullable<long>(3)), "Background", "", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(7, new System.Nullable<long>(5)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "estou autenticado como \"admin@fgcgames.com\" com senha \"Abc!1234\"", null, null, "04850c371f6603538c948cd04150c195"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(8, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "existe um jogo cadastrado com nome \"God of War\"", null, null, "778606c639349858af16dd6970fab00c")}), "c5d5638bac928c5a802868aa6d68a692"), null),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(10, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "Scenario", "Listar todos os jogos retorna 200", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(11, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "listo todos os jogos", null, null, "6f7ab5b9c45e8e5388cb8ebd44f98119"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(12, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "a resposta deve ter status 200", null, null, "423d472f33fd725e908dba2dff155e08"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(13, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "a resposta deve conter uma lista de jogos", null, null, "a7ab81ea1ef5635a97a931b3d5cf8996")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "cad97766b56ef6558b345c191ecf3e09")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(15, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "Scenario", "Buscar jogo por ID existente retorna 200", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(16, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "busco o jogo pelo ID", null, null, "8b544130b819fb5bb8d71505515510de"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(17, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "a resposta deve ter status 200", null, null, "4d35e035d1b953528484321a2b57d64f"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(18, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "a resposta deve conter os dados do jogo", null, null, "f496372795ffc85c8351a35b96ce9d36")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "138a41e86dc9cd5480e9574152869757")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(20, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "Scenario", "Buscar jogo por ID inexistente retorna 404", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(21, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "busco o jogo com ID \"00000000-0000-0000-0000-000000000003\"", null, null, "4bf8ce9c893a825485f34cbae136f617"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(22, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "a resposta deve ter status 404", null, null, "70084a44d3ec4a53bf20efc655fd1ba3")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "d9148be29ec1b455b021122f0272b903")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(24, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "Scenario", "Usuário comum pode listar jogos retorna 200", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(25, new System.Nullable<long>(5)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "estou autenticado como \"user@fgcgames.com\" com senha \"Abc!1234\"", null, null, "0467a3839848e153b65ead17a52ff767"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(26, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "listo todos os jogos", null, null, "3878b4f4c4a730568dfe47d322ea69c0"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(27, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "a resposta deve ter status 200", null, null, "528c2ac3f3d3bd509d23ccad5c5c0570")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "7eabc997e82694568213a2b90ff5c7ca")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(29, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "Scenario", "Requisição sem autenticação não pode listar jogos retorna 401", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(30, new System.Nullable<long>(5)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "não estou autenticado", null, null, "3516b1f1d6d6b25ea4c6600285c631d4"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(31, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "listo todos os jogos", null, null, "266dd7be91706552a7c6c240a691241c"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(32, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "a resposta deve ter status 401", null, null, "c554c8a86cdad85bb6ef3e9d3e02f250")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "f5409e3a3923a1578f5265d23407415d"))})), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Comment>(new global::Io.Cucumber.Messages.Types.Comment[0]));
        }
        
        private static global::System.Collections.Generic.IEnumerable<Io.Cucumber.Messages.Types.Pickle> PicklesFunc()
        {
            return new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Pickle>(new global::Io.Cucumber.Messages.Types.Pickle[] {
                        new global::Io.Cucumber.Messages.Types.Pickle("76765296d5d1ab5ebb5cc9e8710c7b74", "Features/Jogos/BuscarJogo.feature", "Listar todos os jogos retorna 200", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "04850c371f6603538c948cd04150c195"}), "959ca40c3bc8ed5a909ba6b82facb39d", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "estou autenticado como \"admin@fgcgames.com\" com senha \"Abc!1234\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "778606c639349858af16dd6970fab00c"}), "3a8001c7a5035e5e875661319e198ba2", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "existe um jogo cadastrado com nome \"God of War\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "6f7ab5b9c45e8e5388cb8ebd44f98119"}), "bab7a05c50c72457a301386a818f0a50", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "listo todos os jogos"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "423d472f33fd725e908dba2dff155e08"}), "740d381804e047519cbeb21109766f74", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "a resposta deve ter status 200"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "a7ab81ea1ef5635a97a931b3d5cf8996"}), "523dc4e3dc00355c9e2b9c72d312a51c", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "a resposta deve conter uma lista de jogos")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[0]), new System.Collections.Generic.List<string>(new string[] {
                                        "cad97766b56ef6558b345c191ecf3e09"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("216e7548a0c8c053a0521a5a9c50eff7", "Features/Jogos/BuscarJogo.feature", "Buscar jogo por ID existente retorna 200", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "04850c371f6603538c948cd04150c195"}), "fa56bbd68cf4e8588ee01af5ad724933", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "estou autenticado como \"admin@fgcgames.com\" com senha \"Abc!1234\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "778606c639349858af16dd6970fab00c"}), "4c20fa164b6f6e59acd5447b92d265f8", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "existe um jogo cadastrado com nome \"God of War\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "8b544130b819fb5bb8d71505515510de"}), "4869dc1a84d9b553a4944ddc3e82ba5a", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "busco o jogo pelo ID"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "4d35e035d1b953528484321a2b57d64f"}), "104db8f36bdd5459b9f2d544388663d9", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "a resposta deve ter status 200"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "f496372795ffc85c8351a35b96ce9d36"}), "d695cb6e9b30c559ab28d0c59141f363", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "a resposta deve conter os dados do jogo")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[0]), new System.Collections.Generic.List<string>(new string[] {
                                        "138a41e86dc9cd5480e9574152869757"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("b9db0848a68f905c8ad18e345e2b73b1", "Features/Jogos/BuscarJogo.feature", "Buscar jogo por ID inexistente retorna 404", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "04850c371f6603538c948cd04150c195"}), "247e9a408422665b8d20a01f2ee7d985", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "estou autenticado como \"admin@fgcgames.com\" com senha \"Abc!1234\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "778606c639349858af16dd6970fab00c"}), "099f6768f429e25eb8abdce2065c3005", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "existe um jogo cadastrado com nome \"God of War\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "4bf8ce9c893a825485f34cbae136f617"}), "c9c06f3d4c3e5b53bf603ff60b8c2537", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "busco o jogo com ID \"00000000-0000-0000-0000-000000000003\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "70084a44d3ec4a53bf20efc655fd1ba3"}), "db3ed084b4f74053ba6e4561b8da640f", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "a resposta deve ter status 404")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[0]), new System.Collections.Generic.List<string>(new string[] {
                                        "d9148be29ec1b455b021122f0272b903"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("d940a62c05cfa95f8d266f7ba1ec0451", "Features/Jogos/BuscarJogo.feature", "Usuário comum pode listar jogos retorna 200", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "04850c371f6603538c948cd04150c195"}), "521dbfc649d376508308849dd5fa6227", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "estou autenticado como \"admin@fgcgames.com\" com senha \"Abc!1234\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "778606c639349858af16dd6970fab00c"}), "b21191ecb7f7035ea124be12132d17f9", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "existe um jogo cadastrado com nome \"God of War\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "0467a3839848e153b65ead17a52ff767"}), "41b8e3042b3e1358a530632093ad428e", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "estou autenticado como \"user@fgcgames.com\" com senha \"Abc!1234\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "3878b4f4c4a730568dfe47d322ea69c0"}), "90d8719666680456b072b054538c25dd", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "listo todos os jogos"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "528c2ac3f3d3bd509d23ccad5c5c0570"}), "3915e1bd36ff8153b17bfa71b53d4e4c", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "a resposta deve ter status 200")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[0]), new System.Collections.Generic.List<string>(new string[] {
                                        "7eabc997e82694568213a2b90ff5c7ca"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("0f4955f64bc0275b8b3e4ba87d43440c", "Features/Jogos/BuscarJogo.feature", "Requisição sem autenticação não pode listar jogos retorna 401", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "04850c371f6603538c948cd04150c195"}), "5783415a22dd0d54832381c73c7ed0ea", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "estou autenticado como \"admin@fgcgames.com\" com senha \"Abc!1234\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "778606c639349858af16dd6970fab00c"}), "48e39fd5eda2025986947151eb5afb0b", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "existe um jogo cadastrado com nome \"God of War\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "3516b1f1d6d6b25ea4c6600285c631d4"}), "45ab1fdd4865a65483233e180521c423", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "não estou autenticado"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "266dd7be91706552a7c6c240a691241c"}), "53f1c328d6fa3a5fb1cd6acb426ee912", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "listo todos os jogos"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "c554c8a86cdad85bb6ef3e9d3e02f250"}), "daaa2cbbf90a865490dcd38f1facf91c", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "a resposta deve ter status 401")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[0]), new System.Collections.Generic.List<string>(new string[] {
                                        "f5409e3a3923a1578f5265d23407415d"}))});
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages(new global::System.Func<Io.Cucumber.Messages.Types.Source>(BuscarJogoFeature.SourceFunc), new global::System.Func<Io.Cucumber.Messages.Types.GherkinDocument>(BuscarJogoFeature.GherkinDocumentFunc), new global::System.Func<System.Collections.Generic.IEnumerable<Io.Cucumber.Messages.Types.Pickle>>(BuscarJogoFeature.PicklesFunc));
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Listar todos os jogos retorna 200")]
        public async global::System.Threading.Tasks.Task ListarTodosOsJogosRetorna200()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Listar todos os jogos retorna 200", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 10
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 11
    await testRunner.WhenAsync("listo todos os jogos", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 12
    await testRunner.ThenAsync("a resposta deve ter status 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 13
    await testRunner.AndAsync("a resposta deve conter uma lista de jogos", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Buscar jogo por ID existente retorna 200")]
        public async global::System.Threading.Tasks.Task BuscarJogoPorIDExistenteRetorna200()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Buscar jogo por ID existente retorna 200", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 15
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 16
    await testRunner.WhenAsync("busco o jogo pelo ID", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 17
    await testRunner.ThenAsync("a resposta deve ter status 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 18
    await testRunner.AndAsync("a resposta deve conter os dados do jogo", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Buscar jogo por ID inexistente retorna 404")]
        public async global::System.Threading.Tasks.Task BuscarJogoPorIDInexistenteRetorna404()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Buscar jogo por ID inexistente retorna 404", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 20
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 21
    await testRunner.WhenAsync("busco o jogo com ID \"00000000-0000-0000-0000-000000000003\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 22
    await testRunner.ThenAsync("a resposta deve ter status 404", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Usuário comum pode listar jogos retorna 200")]
        public async global::System.Threading.Tasks.Task UsuarioComumPodeListarJogosRetorna200()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "3";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Usuário comum pode listar jogos retorna 200", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 24
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 25
    await testRunner.GivenAsync("estou autenticado como \"user@fgcgames.com\" com senha \"Abc!1234\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 26
    await testRunner.WhenAsync("listo todos os jogos", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 27
    await testRunner.ThenAsync("a resposta deve ter status 200", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Requisição sem autenticação não pode listar jogos retorna 401")]
        public async global::System.Threading.Tasks.Task RequisicaoSemAutenticacaoNaoPodeListarJogosRetorna401()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "4";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Requisição sem autenticação não pode listar jogos retorna 401", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 29
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 30
    await testRunner.GivenAsync("não estou autenticado", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 31
    await testRunner.WhenAsync("listo todos os jogos", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 32
    await testRunner.ThenAsync("a resposta deve ter status 401", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
