// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:3.0.0.0
//      Reqnroll Generator Version:3.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace FgcGames.BDDTests.Features.Jogos
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "3.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::NUnit.Framework.TestFixtureAttribute()]
    [global::NUnit.Framework.DescriptionAttribute("Criar Jogo")]
    [global::NUnit.Framework.FixtureLifeCycleAttribute(global::NUnit.Framework.LifeCycle.InstancePerTestCase)]
    public partial class CriarJogoFeature
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("en-US"), "Features/Jogos", "Criar Jogo", "  Como administrador do sistema\r\n  Quero cadastrar novos jogos\r\n  Para disponibil" +
                "izá-los na plataforma", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags, InitializeCucumberMessages());
        
#line 1 "CriarJogo.feature"
#line hidden
        
        [global::NUnit.Framework.OneTimeSetUpAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        [global::NUnit.Framework.OneTimeTearDownAttribute()]
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
            await global::Reqnroll.TestRunnerManager.ReleaseFeatureAsync(featureInfo);
        }
        
        [global::NUnit.Framework.SetUpAttribute()]
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        [global::NUnit.Framework.TearDownAttribute()]
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo, global::Reqnroll.RuleInfo ruleInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo, ruleInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<global::NUnit.Framework.TestContext>(global::NUnit.Framework.TestContext.CurrentContext);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        public virtual async global::System.Threading.Tasks.Task FeatureBackgroundAsync()
        {
#line 6
  #line hidden
#line 7
    await testRunner.GivenAsync("estou autenticado como \"admin@fgcgames.com\" com senha \"Abc!1234\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
        }
        
        private static global::Io.Cucumber.Messages.Types.Source SourceFunc()
        {
            return new global::Io.Cucumber.Messages.Types.Source("Features/Jogos/CriarJogo.feature", @"Feature: Criar Jogo
  Como administrador do sistema
  Quero cadastrar novos jogos
  Para disponibilizá-los na plataforma

  Background:
    Given estou autenticado como ""admin@fgcgames.com"" com senha ""Abc!1234""

  Scenario: Admin cria jogo com dados válidos retorna 201
    When crio um jogo com nome ""The Witcher 3"", descrição ""RPG de mundo aberto"", preço 199.90, lançamento ""2015-05-19"" e classificação 18
    Then a resposta deve ter status 201
    And a resposta deve conter um ID de jogo válido

  Scenario: Usuário comum não pode criar jogo retorna 403
    Given estou autenticado como ""user@fgcgames.com"" com senha ""Abc!1234""
    When crio um jogo com nome ""Jogo Teste"", descrição ""Desc"", preço 99.90, lançamento ""2020-01-01"" e classificação 0
    Then a resposta deve ter status 403

  Scenario: Requisição sem autenticação não pode criar jogo retorna 401
    Given não estou autenticado
    When crio um jogo com nome ""Jogo Teste"", descrição ""Desc"", preço 99.90, lançamento ""2020-01-01"" e classificação 0
    Then a resposta deve ter status 401
", global::Io.Cucumber.Messages.Types.SourceMediaType.TEXT_X_CUCUMBER_GHERKIN_PLAIN);
        }
        
        private static global::Io.Cucumber.Messages.Types.GherkinDocument GherkinDocumentFunc()
        {
            return new global::Io.Cucumber.Messages.Types.GherkinDocument("Features/Jogos/CriarJogo.feature", new global::Io.Cucumber.Messages.Types.Feature(new global::Io.Cucumber.Messages.Types.Location(1, new System.Nullable<long>(1)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "en-US", "Feature", "Criar Jogo", "  Como administrador do sistema\r\n  Quero cadastrar novos jogos\r\n  Para disponibil" +
                        "izá-los na plataforma", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.FeatureChild>(new global::Io.Cucumber.Messages.Types.FeatureChild[] {
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, new global::Io.Cucumber.Messages.Types.Background(new global::Io.Cucumber.Messages.Types.Location(6, new System.Nullable<long>(3)), "Background", "", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(7, new System.Nullable<long>(5)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "estou autenticado como \"admin@fgcgames.com\" com senha \"Abc!1234\"", null, null, "d5838645f1a03a509c19fbb883acd637")}), "9960f97931528e5f8039c93e571323cd"), null),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(9, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "Scenario", "Admin cria jogo com dados válidos retorna 201", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(10, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "crio um jogo com nome \"The Witcher 3\", descrição \"RPG de mundo aberto\", preço 199" +
                                                            ".90, lançamento \"2015-05-19\" e classificação 18", null, null, "991f8119c1016a5aba429244b3bb8bfa"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(11, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "a resposta deve ter status 201", null, null, "22edc8c36513c257b2c57349400851ce"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(12, new System.Nullable<long>(5)), "And ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONJUNCTION, "a resposta deve conter um ID de jogo válido", null, null, "0c8f75d81acb605399562d5a50ff6093")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "16f67cbf5517d953bf5f9df36141b829")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(14, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "Scenario", "Usuário comum não pode criar jogo retorna 403", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(15, new System.Nullable<long>(5)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "estou autenticado como \"user@fgcgames.com\" com senha \"Abc!1234\"", null, null, "13de5d4d71366857bf12ebd35ebe62ef"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(16, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "crio um jogo com nome \"Jogo Teste\", descrição \"Desc\", preço 99.90, lançamento \"20" +
                                                            "20-01-01\" e classificação 0", null, null, "07167d18c12e05588e4c1834655e50d4"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(17, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "a resposta deve ter status 403", null, null, "d05891583f8c0f5a8261525f8b00da23")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "abf665f1062c8858ab20847fb3b8899a")),
                                new global::Io.Cucumber.Messages.Types.FeatureChild(null, null, new global::Io.Cucumber.Messages.Types.Scenario(new global::Io.Cucumber.Messages.Types.Location(19, new System.Nullable<long>(3)), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Tag>(new global::Io.Cucumber.Messages.Types.Tag[0]), "Scenario", "Requisição sem autenticação não pode criar jogo retorna 401", "", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Step>(new global::Io.Cucumber.Messages.Types.Step[] {
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(20, new System.Nullable<long>(5)), "Given ", global::Io.Cucumber.Messages.Types.StepKeywordType.CONTEXT, "não estou autenticado", null, null, "cabf448b9b9ebd528cb491dbf2d9f97a"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(21, new System.Nullable<long>(5)), "When ", global::Io.Cucumber.Messages.Types.StepKeywordType.ACTION, "crio um jogo com nome \"Jogo Teste\", descrição \"Desc\", preço 99.90, lançamento \"20" +
                                                            "20-01-01\" e classificação 0", null, null, "88b9c025952455538190cb898957dc60"),
                                                    new global::Io.Cucumber.Messages.Types.Step(new global::Io.Cucumber.Messages.Types.Location(22, new System.Nullable<long>(5)), "Then ", global::Io.Cucumber.Messages.Types.StepKeywordType.OUTCOME, "a resposta deve ter status 401", null, null, "201469a84050d351a6df429a523beb2d")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Examples>(new global::Io.Cucumber.Messages.Types.Examples[0]), "902e533d065be15587599c800ffe63b3"))})), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Comment>(new global::Io.Cucumber.Messages.Types.Comment[0]));
        }
        
        private static global::System.Collections.Generic.IEnumerable<Io.Cucumber.Messages.Types.Pickle> PicklesFunc()
        {
            return new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.Pickle>(new global::Io.Cucumber.Messages.Types.Pickle[] {
                        new global::Io.Cucumber.Messages.Types.Pickle("e2412b731f33ae5e98ef8c3a0630c352", "Features/Jogos/CriarJogo.feature", "Admin cria jogo com dados válidos retorna 201", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "d5838645f1a03a509c19fbb883acd637"}), "5ea183058cf5195e8e6a7d4cad8823b1", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "estou autenticado como \"admin@fgcgames.com\" com senha \"Abc!1234\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "991f8119c1016a5aba429244b3bb8bfa"}), "ef6bf74cadc71f5f85b0d60e71618315", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "crio um jogo com nome \"The Witcher 3\", descrição \"RPG de mundo aberto\", preço 199" +
                                                ".90, lançamento \"2015-05-19\" e classificação 18"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "22edc8c36513c257b2c57349400851ce"}), "aec31f10cda1355b88f5acc0f0b6a33d", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "a resposta deve ter status 201"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "0c8f75d81acb605399562d5a50ff6093"}), "02b26c8f4a19d452b745d5bd582c90b4", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "a resposta deve conter um ID de jogo válido")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[0]), new System.Collections.Generic.List<string>(new string[] {
                                        "16f67cbf5517d953bf5f9df36141b829"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("72a66a4d2a456b549123cd77e63d6209", "Features/Jogos/CriarJogo.feature", "Usuário comum não pode criar jogo retorna 403", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "d5838645f1a03a509c19fbb883acd637"}), "782795a5a2ae8a52b38f05d4477b925a", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "estou autenticado como \"admin@fgcgames.com\" com senha \"Abc!1234\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "13de5d4d71366857bf12ebd35ebe62ef"}), "ac27b1ff6897605eaa7fe6a5b9503c1e", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "estou autenticado como \"user@fgcgames.com\" com senha \"Abc!1234\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "07167d18c12e05588e4c1834655e50d4"}), "6e2d38aca97bd353ad1ee6450554c11c", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "crio um jogo com nome \"Jogo Teste\", descrição \"Desc\", preço 99.90, lançamento \"20" +
                                                "20-01-01\" e classificação 0"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "d05891583f8c0f5a8261525f8b00da23"}), "3ae936a868c89a5abecd5475edae37b2", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "a resposta deve ter status 403")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[0]), new System.Collections.Generic.List<string>(new string[] {
                                        "abf665f1062c8858ab20847fb3b8899a"})),
                        new global::Io.Cucumber.Messages.Types.Pickle("79479870bd6fd55b9f4c6b046e69638e", "Features/Jogos/CriarJogo.feature", "Requisição sem autenticação não pode criar jogo retorna 401", "en-US", new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleStep>(new global::Io.Cucumber.Messages.Types.PickleStep[] {
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "d5838645f1a03a509c19fbb883acd637"}), "9e97d7670515a25fbbf5f95a307d898f", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "estou autenticado como \"admin@fgcgames.com\" com senha \"Abc!1234\""),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "cabf448b9b9ebd528cb491dbf2d9f97a"}), "bdbae1872b23b15c8f74c4999d8d4e01", global::Io.Cucumber.Messages.Types.PickleStepType.CONTEXT, "não estou autenticado"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "88b9c025952455538190cb898957dc60"}), "6bbf4f4c96e4ad519b2dfbcdfe3a4da6", global::Io.Cucumber.Messages.Types.PickleStepType.ACTION, "crio um jogo com nome \"Jogo Teste\", descrição \"Desc\", preço 99.90, lançamento \"20" +
                                                "20-01-01\" e classificação 0"),
                                        new global::Io.Cucumber.Messages.Types.PickleStep(null, new System.Collections.Generic.List<string>(new string[] {
                                                        "201469a84050d351a6df429a523beb2d"}), "e528ef741053775fb09ded78efeeb3f9", global::Io.Cucumber.Messages.Types.PickleStepType.OUTCOME, "a resposta deve ter status 401")}), new System.Collections.Generic.List<global::Io.Cucumber.Messages.Types.PickleTag>(new global::Io.Cucumber.Messages.Types.PickleTag[0]), new System.Collections.Generic.List<string>(new string[] {
                                        "902e533d065be15587599c800ffe63b3"}))});
        }
        
        private static global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages InitializeCucumberMessages()
        {
            return new global::Reqnroll.Formatters.RuntimeSupport.FeatureLevelCucumberMessages(new global::System.Func<Io.Cucumber.Messages.Types.Source>(CriarJogoFeature.SourceFunc), new global::System.Func<Io.Cucumber.Messages.Types.GherkinDocument>(CriarJogoFeature.GherkinDocumentFunc), new global::System.Func<System.Collections.Generic.IEnumerable<Io.Cucumber.Messages.Types.Pickle>>(CriarJogoFeature.PicklesFunc));
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Admin cria jogo com dados válidos retorna 201")]
        public async global::System.Threading.Tasks.Task AdminCriaJogoComDadosValidosRetorna201()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "0";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Admin cria jogo com dados válidos retorna 201", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 9
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 10
    await testRunner.WhenAsync("crio um jogo com nome \"The Witcher 3\", descrição \"RPG de mundo aberto\", preço 199" +
                        ".90, lançamento \"2015-05-19\" e classificação 18", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 11
    await testRunner.ThenAsync("a resposta deve ter status 201", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
#line 12
    await testRunner.AndAsync("a resposta deve conter um ID de jogo válido", ((string)(null)), ((global::Reqnroll.Table)(null)), "And ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Usuário comum não pode criar jogo retorna 403")]
        public async global::System.Threading.Tasks.Task UsuarioComumNaoPodeCriarJogoRetorna403()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "1";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Usuário comum não pode criar jogo retorna 403", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 14
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 15
    await testRunner.GivenAsync("estou autenticado como \"user@fgcgames.com\" com senha \"Abc!1234\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 16
    await testRunner.WhenAsync("crio um jogo com nome \"Jogo Teste\", descrição \"Desc\", preço 99.90, lançamento \"20" +
                        "20-01-01\" e classificação 0", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 17
    await testRunner.ThenAsync("a resposta deve ter status 403", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::NUnit.Framework.TestAttribute()]
        [global::NUnit.Framework.DescriptionAttribute("Requisição sem autenticação não pode criar jogo retorna 401")]
        public async global::System.Threading.Tasks.Task RequisicaoSemAutenticacaoNaoPodeCriarJogoRetorna401()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            string pickleIndex = "2";
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Requisição sem autenticação não pode criar jogo retorna 401", null, tagsOfScenario, argumentsOfScenario, featureTags, pickleIndex);
            string[] tagsOfRule = ((string[])(null));
            global::Reqnroll.RuleInfo ruleInfo = null;
#line 19
  this.ScenarioInitialize(scenarioInfo, ruleInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                await testRunner.SkipScenarioAsync();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 6
  await this.FeatureBackgroundAsync();
#line hidden
#line 20
    await testRunner.GivenAsync("não estou autenticado", ((string)(null)), ((global::Reqnroll.Table)(null)), "Given ");
#line hidden
#line 21
    await testRunner.WhenAsync("crio um jogo com nome \"Jogo Teste\", descrição \"Desc\", preço 99.90, lançamento \"20" +
                        "20-01-01\" e classificação 0", ((string)(null)), ((global::Reqnroll.Table)(null)), "When ");
#line hidden
#line 22
    await testRunner.ThenAsync("a resposta deve ter status 401", ((string)(null)), ((global::Reqnroll.Table)(null)), "Then ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
    }
}
#pragma warning restore
#endregion
