name: 🧪 Unit Tests

on:
  pull_request:

  push:
    branches-ignore:
      - main
      - develop

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout do código
        uses: actions/checkout@v4

      - name: ⚙️ Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x

      - name: 📦 Restore
        run: dotnet restore --verbosity minimal

      - name: 🧪 Rodar testes unitários
        run: dotnet test tests/FgcGames.UnitTests/FgcGames.UnitTests.csproj --verbosity normal
